import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import AppWalletProvider from "./components/AppWalletProvider"; // <--- Import this

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solana Token Launchpad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWalletProvider> {}
          {children}
        </AppWalletProvider>
      </body>
    </html>
  );
}
